CursosBundle\Entity\Usuario:
    type: entity
    table: usuario
    repositoryClass: CursosBundle\Repository\UsuarioRepository
    indexes:
        fk_usuario_persona:
            columns:
                - persona_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rol:
            type: string
            length: '20'
        apodo:
            type: string
            length: '40'
            unique: true
        correo:
            type: string
            length: '80'
            unique: true
        password:
            type: string
            length: '80'
    manyToOne:
        persona:
            targetEntity: Persona
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: usuario
            joinColumns:
                persona_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
