CursosBundle\Entity\Usuario:
  properties:
    apodo:
      - NotBlank: {message: "Debe introducir un apodo"}
      - Length:
          min: 4
          minMessage: "El apodo debe ser de al menos 4 caracteres"
    correo:
      - Email:
          message: "Introduzca un email v치lido"
      - NotBlank: {message: "Debe introducir su correo electr칩nico"}
    password:
      - NotBlank: {message: "Debe introducir una contrase침a"}
      - Length:
          min: 4
          minMessage: "La contrase침a debe ser de al menos 4 caracteres"
